---
title: ""
format: 
  html:
    css: "styles.css"
---

## X Congreso de la Red Española de Política Social (REPS) 2025

**Logroño, 22-24 de octubre de 2025**

## Panel 10 \| Las políticas educativas y de protección a la infancia: interrelación e impactos

::: panel-tabset
## **Descripción del panel**

**Coordinadores:** Sheila González Motos (Universitat de Barcelona) y Adrián Zancajo (Universitat Autònoma de Barcelona)

Las condiciones sociales interfieren significativamente en las probabilidades de obtener el graduado escolar, en el riesgo de repetición de curso, en la transición a la educación postobligatoria o en el acceso a la universidad. Todo ello demuestra que el diseño de nuestro sistema educativo tiene limitaciones para garantizar la igualdad de oportunidades para los niños y niñas de entornos más vulnerables. La interrelación entre desigualdad social y desigualdad educativa ha motivado que muchas de las políticas compensatorias implementadas en el entorno escolar posean una doble naturaleza, buscando no solo mitigar las desigualdades educativas, sino también abordar problemáticas sociales más amplias que afectan a la infancia.

El panel propone un enfoque interdisciplinario para el análisis de las políticas sociales dirigidas a la infancia que impactan o pueden impactar en el ámbito educativo. Este enfoque pretende promover un diálogo más fluido entre disciplinas como la sociología, las ciencias políticas y la economía, que tradicionalmente han abordado estas cuestiones desde perspectivas aisladas. El objetivo del panel es profundizar en marcos analíticos y conceptuales que permitan analizar el diseño, la implementación y los impactos de las políticas públicas dirigidas a la infancia que superen los límites entre lo educativo y lo social. De esta manera, se podrán abordar de forma más integral el análisis de los desafíos que enfrenta la infancia en relación con la pobreza, la exclusión social, las desigualdades educativas y otras formas de vulnerabilidad. Más allá del ámbito estrictamente académico, el panel invita también a la reflexión sobre cómo el diseño e implementación de políticas sociales y educativas pueden contribuir a una infancia más equitativa y socialmente protegida, facilitando un intercambio de ideas que propicie la innovación en políticas públicas.

Este panel tiene por objetivo reunir trabajos sobre políticas públicas que den muestra de la interrelación entre las políticas públicas educativas y de protección social que tienen por objetivo la reducción de la vulnerabilidad en la infancia. Por ello, el panel incluirá investigaciones que analicen políticas sociales dirigidas a la infancia, con especial énfasis en su relación con el ámbito educativo, así como, trabajos que, partiendo del ámbito de las políticas educativas, impliquen una dimensión social. En concreto, el panel incluirá: i) Análisis de políticas educativas que contemplen la compensación de desigualdades de carácter social, ii) Análisis de políticas sociales que impacten en el ámbito educativo, iii) Análisis de la interrelación del ámbito social y educativo

**Palabras clave:** Infancia, Vulnerabilidad infantil, Políticas educativas compensatorias, Desigualdades sociales en la infancia, Políticas públicas

## Envío de propuestas

Las propuestas de comunicaciones para el panel se deben enviar a través del [formulario disponible en la página de web del congreso](https://reps2025.unirioja.es/es/pages/comunicaciones) antes del **31 de enero de 2025.**

## Contacto coordinadores

En caso de cualquier pregunta o duda sobre el panel, por favor, no dude en contactar con los coordinadores: Sheila González Motos (sheila.gonzalez\@ub.edu) y Adrián Zancajo (adrian.zancajo\@gmail.com)

## Información sobre el congreso

Toda la información sobre el congreso (fechas, inscripción, alojamiento, etc.) está disponible en la [página web del congreso](https://reps2025.unirioja.es/)
:::
